name: "CI for builds"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install dependencies
        run: go get .
      - name: Build
        run: env GOOS=${{matrix.os}} GOARCH=${{arch}} go build -o go-transcode-${{os}}-${{arch}}
