name: "CI for builds"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin]
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install dependencies
        run: go get .
      - name: Build
        run: env GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o go-transcode-${{matrix.os}}-${{matrix.arch}}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: go-transcode-${{matrix.os}}-${{matrix.arch}}
          asset_name: go-transcode-${{matrix.os}}-${{matrix.arch}}
          tag: ${{ github.ref }}
          overwrite: true
